"""rename session column

Revision ID: 6a4cd6eaefcd
Revises: 1936612c05dc
Create Date: 2022-07-11 20:31:54.871428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a4cd6eaefcd'
down_revision = '1936612c05dc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ntlm_brute_session', sa.Column('session_name', sa.String(), nullable=True))
    op.drop_column('ntlm_brute_session', 'session')
    op.add_column('ntlm_dump_session', sa.Column('session_name', sa.String(), nullable=True))
    op.drop_column('ntlm_dump_session', 'session')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ntlm_dump_session', sa.Column('session', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('ntlm_dump_session', 'session_name')
    op.add_column('ntlm_brute_session', sa.Column('session', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('ntlm_brute_session', 'session_name')
    # ### end Alembic commands ###
