"""rename clmn in ntlm_dump_hash tbl

Revision ID: 9773fc047229
Revises: ba61b4f55a1f
Create Date: 2022-07-13 13:58:55.459736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9773fc047229'
down_revision = 'ba61b4f55a1f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ntlm_dump_hash', sa.Column('user_ntlm_hash', sa.String(), nullable=True))
    op.drop_column('ntlm_dump_hash', 'user_pass_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ntlm_dump_hash', sa.Column('user_pass_hash', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('ntlm_dump_hash', 'user_ntlm_hash')
    # ### end Alembic commands ###
