"""add pk column

Revision ID: afeaa5fcdb4d
Revises: efcb99a42faa
Create Date: 2022-07-11 19:24:21.098911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afeaa5fcdb4d'
down_revision = 'efcb99a42faa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ntlm_brute_session', sa.Column('domain_name', sa.String(), nullable=True))
    op.add_column('ntlm_brute_session', sa.Column('domain_pk', sa.Integer(), nullable=True))
    op.drop_column('ntlm_brute_session', 'domain')
    op.add_column('ntlm_dump_session', sa.Column('domain_name', sa.String(), nullable=True))
    op.add_column('ntlm_dump_session', sa.Column('domain_pk', sa.Integer(), nullable=True))
    op.drop_column('ntlm_dump_session', 'domain')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ntlm_dump_session', sa.Column('domain', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('ntlm_dump_session', 'domain_pk')
    op.drop_column('ntlm_dump_session', 'domain_name')
    op.add_column('ntlm_brute_session', sa.Column('domain', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('ntlm_brute_session', 'domain_pk')
    op.drop_column('ntlm_brute_session', 'domain_name')
    # ### end Alembic commands ###
