"""add ntlm_dump_hash tbl

Revision ID: ba61b4f55a1f
Revises: 6a4cd6eaefcd
Create Date: 2022-07-13 13:35:37.812470

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ba61b4f55a1f'
down_revision = '6a4cd6eaefcd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ntlm_dump_hash',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain_pk', sa.Integer(), nullable=True),
    sa.Column('user_login', sa.String(), nullable=True),
    sa.Column('user_pass_hash', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_table('ntlm_dump_hash')
    # ### end Alembic commands ###
