"""init_models

Revision ID: efcb99a42faa
Revises: 
Create Date: 2022-07-11 19:10:36.357500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efcb99a42faa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ntlm_brute_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session', sa.String(), nullable=True),
    sa.Column('domain', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ntlm_dump_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session', sa.String(), nullable=True),
    sa.Column('domain', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ntlm_dump_session')
    op.drop_table('ntlm_brute_session')
    # ### end Alembic commands ###
